// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemInfoRequest {
    #[prost(string, tag = "1")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub os: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub uptime_seconds: u64,
    #[prost(string, tag = "4")]
    pub kernel_version: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub cpu_model: ::prost::alloc::string::String,
    #[prost(uint32, tag = "6")]
    pub cpu_count: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetricsRequest {
    #[prost(message, optional, tag = "8")]
    pub cpu_stats: ::core::option::Option<CpuStats>,
    #[prost(message, optional, tag = "9")]
    pub memory_stats: ::core::option::Option<MemoryStats>,
    #[prost(message, repeated, tag = "10")]
    pub disk_stats: ::prost::alloc::vec::Vec<DiskStats>,
    #[prost(message, repeated, tag = "11")]
    pub components: ::prost::alloc::vec::Vec<Component>,
    #[prost(message, optional, tag = "12")]
    pub network_stats: ::core::option::Option<NetworkStats>,
    #[prost(message, optional, tag = "13")]
    pub load_average: ::core::option::Option<LoadAverage>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemctlRequest {
    #[prost(message, repeated, tag = "1")]
    pub services: ::prost::alloc::vec::Vec<SystemService>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemService {
    #[prost(string, tag = "1")]
    pub service_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub pid: u64,
    #[prost(string, tag = "4")]
    pub state: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub cpu: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub memory: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemctlResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CpuStats {
    #[prost(double, tag = "1")]
    pub usage_percent: f64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MemoryStats {
    #[prost(uint64, tag = "1")]
    pub total_kb: u64,
    #[prost(uint64, tag = "2")]
    pub used_kb: u64,
    #[prost(uint64, tag = "3")]
    pub free_kb: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DiskStats {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub total_space: i32,
    #[prost(int32, tag = "3")]
    pub used_space: i32,
    #[prost(string, tag = "4")]
    pub unit: ::prost::alloc::string::String,
    #[prost(double, tag = "5")]
    pub read_bytes: f64,
    #[prost(double, tag = "6")]
    pub write_bytes: f64,
    #[prost(string, tag = "7")]
    pub mount_point: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LoadAverage {
    #[prost(double, tag = "1")]
    pub one_minute: f64,
    #[prost(double, tag = "2")]
    pub five_minutes: f64,
    #[prost(double, tag = "3")]
    pub fifteen_minutes: f64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct NetworkStats {
    #[prost(uint64, tag = "1")]
    pub r#in: u64,
    #[prost(uint64, tag = "2")]
    pub out: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Component {
    #[prost(string, tag = "1")]
    pub label: ::prost::alloc::string::String,
    #[prost(float, tag = "2")]
    pub temperature: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetricsResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemInfoResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod system_monitor_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct SystemMonitorClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl SystemMonitorClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> SystemMonitorClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> SystemMonitorClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            SystemMonitorClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn report_metrics(
            &mut self,
            request: impl tonic::IntoRequest<super::MetricsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::MetricsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/monitor.SystemMonitor/ReportMetrics",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("monitor.SystemMonitor", "ReportMetrics"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_system_info(
            &mut self,
            request: impl tonic::IntoRequest<super::SystemInfoRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SystemInfoResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/monitor.SystemMonitor/GetSystemInfo",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("monitor.SystemMonitor", "GetSystemInfo"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn report_systemctl(
            &mut self,
            request: impl tonic::IntoRequest<super::SystemctlRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SystemctlResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/monitor.SystemMonitor/ReportSystemctl",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("monitor.SystemMonitor", "ReportSystemctl"));
            self.inner.unary(req, path, codec).await
        }
    }
}
